name: Formatting

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  format-frontend:
    name: Format Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier and auto-fix
        run: npx prettier --write .

      - name: Commit and push formatted frontend
        run: ../scripts/commit-format-frontend.sh

  format-backend:
    name: Format Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make Maven wrapper executable
        run: chmod +x ./mvnw

      - name: Apply Spotless formatting
        run: ./mvnw spotless:apply

      - name: Commit and push formatted backend
        run: ../scripts/commit-format-backend.sh

